"""TaskReference for type-safe task execution.

This module provides the TaskReference class that enables type-safe
task execution from workflows.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Generic, TypeVar

if TYPE_CHECKING:
    from orcher.decorators.registry import TaskMetadata

__all__ = ["TaskReference"]

TInput = TypeVar("TInput")
TOutput = TypeVar("TOutput")


class TaskReference(Generic[TInput, TOutput]):
    """Type-safe reference to a task.

    TaskReference is automatically generated by the @task decorator and
    attached as a class attribute to enable type-safe task execution.

    The generic parameters TInput and TOutput capture the task's input
    and output types for IDE type inference.

    Attributes:
        task_name: The registered name of the task.
        handler_class: The class containing the task method.
        method_name: The name of the task method.
        __orcher_task__: The task's registered metadata, as a function decorated
            with ``@task`` carries it, so a workflow reads the declared return type
            from either one the same way.

    Example:
        >>> from orcher import task, TaskContext
        >>>
        >>> class PaymentTasks:
        ...     @task(name="charge-card")
        ...     async def charge_card(self, ctx: TaskContext, amount: int) -> str:
        ...         return f"charged-{amount}"
        >>>
        >>> # TaskReference is automatically created:
        >>> # PaymentTasks.charge_card is TaskReference[int, str]
        >>>
        >>> # In a workflow:
        >>> result = await ctx.execute_task(PaymentTasks.charge_card, 100)
        >>> # result is typed as str!
    """

    def __init__(
        self,
        task_name: str,
        handler_class: type[Any],
        method_name: str,
        metadata: TaskMetadata | None = None,
    ) -> None:
        """Initialize a TaskReference.

        Args:
            task_name: The registered name of the task.
            handler_class: The class containing the task method.
            method_name: The name of the task method.
            metadata: The task's registered metadata.
        """
        self._task_name = task_name
        self._handler_class = handler_class
        self._method_name = method_name
        self.__orcher_task__ = metadata

    @property
    def task_name(self) -> str:
        """Get the task name."""
        return self._task_name

    @property
    def handler_class(self) -> type[Any]:
        """Get the handler class."""
        return self._handler_class

    @property
    def method_name(self) -> str:
        """Get the method name."""
        return self._method_name

    def __repr__(self) -> str:
        return (
            f"TaskReference("
            f"task_name={self._task_name!r}, "
            f"handler={self._handler_class.__name__}.{self._method_name}"
            f")"
        )

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, TaskReference):
            return NotImplemented
        return (
            self._task_name == other._task_name
            and self._handler_class == other._handler_class
            and self._method_name == other._method_name
        )

    def __hash__(self) -> int:
        return hash((self._task_name, self._handler_class, self._method_name))

    # Phantom attributes that carry the generic parameters for type checkers.
    if TYPE_CHECKING:
        _input_type: TInput
        _output_type: TOutput
