"""Workflow execution types for the Orcher Python SDK.

This module provides the WorkflowExecution dataclass and related types
for identifying and tracking workflow executions.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any

__all__ = [
    "WorkflowExecution",
    "WorkflowExecutionStatus",
    "WorkflowExecutionInfo",
]


class WorkflowExecutionStatus(Enum):
    """Status of a workflow execution."""

    UNKNOWN = "unknown"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"
    TERMINATED = "terminated"
    CONTINUED_AS_NEW = "continued_as_new"
    TIMED_OUT = "timed_out"


@dataclass(frozen=True)
class WorkflowExecution:
    """Identifier for a workflow execution.

    A workflow execution is uniquely identified by the combination of
    workflow_id and run_id. The workflow_id is user-provided while
    run_id is generated by the server for each execution attempt.

    Attributes:
        workflow_id: User-provided unique identifier for the workflow.
        run_id: Server-generated identifier for this specific execution.
    """

    workflow_id: str
    run_id: str | None = None

    def __str__(self) -> str:
        if self.run_id:
            return f"{self.workflow_id}:{self.run_id}"
        return self.workflow_id

    def __repr__(self) -> str:
        return f"WorkflowExecution(workflow_id={self.workflow_id!r}, run_id={self.run_id!r})"


@dataclass
class WorkflowExecutionInfo:
    """Detailed information about a workflow execution.

    This provides comprehensive information about a workflow execution,
    including its current status, timing information, and metadata.

    Attributes:
        execution: The workflow execution identifier.
        workflow_type: The type/name of the workflow.
        task_queue: The task queue the workflow runs on.
        namespace: The namespace of the workflow.
        status: Current execution status.
        start_time: When the execution started.
        close_time: When the execution completed (if finished).
        history_length: Number of events in the execution history.
        memo: User-provided metadata.
        labels: Searchable attributes for visibility.
        parent_execution: Parent workflow execution (if this is a child).
    """

    execution: WorkflowExecution
    workflow_type: str
    task_queue: str
    namespace: str
    status: WorkflowExecutionStatus = WorkflowExecutionStatus.UNKNOWN
    start_time: datetime | None = None
    close_time: datetime | None = None
    history_length: int = 0
    memo: dict[str, Any] | None = None
    labels: dict[str, Any] | None = None
    parent_execution: WorkflowExecution | None = None

    @property
    def workflow_id(self) -> str:
        """Get the workflow ID."""
        return self.execution.workflow_id

    @property
    def run_id(self) -> str | None:
        """Get the run ID."""
        return self.execution.run_id

    @property
    def is_running(self) -> bool:
        """Check if the workflow is still running."""
        return self.status == WorkflowExecutionStatus.RUNNING

    @property
    def is_completed(self) -> bool:
        """Check if the workflow completed successfully."""
        return self.status == WorkflowExecutionStatus.COMPLETED

    @property
    def is_failed(self) -> bool:
        """Check if the workflow failed."""
        return self.status == WorkflowExecutionStatus.FAILED

    @property
    def is_finished(self) -> bool:
        """Check if the workflow has finished (any terminal state)."""
        return self.status in (
            WorkflowExecutionStatus.COMPLETED,
            WorkflowExecutionStatus.FAILED,
            WorkflowExecutionStatus.CANCELLED,
            WorkflowExecutionStatus.TERMINATED,
            WorkflowExecutionStatus.TIMED_OUT,
        )
